=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/schema/courtscheduler.crown.search.and.book.response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "hearingId": {
      "type": "string"
    },
    "courtScheduleId": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "sessions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "courtScheduleId": {
            "type": "string"
          },
          "sessionDate": {
            "type": "string",
            "format": "date"
          },
          "courtRoomId": {
            "type": "string"
          },
          "businessType": {
            "type": "string"
          },
          "isDraft": {
            "type": "boolean"
          }
        }
      }
    },
    "courtRoomId": {
      "type": "integer"
    },
    "sessionDate": {
      "type": "string",
      "format": "date"
    },
    "sessionStartTime": {
      "type": "string"
    },
    "sessionEndTime": {
      "type": "string"
    },
    "durationInMinutes": {
      "type": "integer"
    },
    "isDraft": {
      "type": "boolean"
    },
    "businessType": {
      "type": "string"
    },
    "overbooked": {
      "type": "boolean"
    }
  },
  "required": [
    "hearingId",
    "sessions"
  ]
}

=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/courtscheduler.crown.search.and.book.response.json
{
  "hearingId": "7755fb96-e90a-4df2-8575-47841d8fbdd0",
  "courtScheduleId": "5e2a3f91-9e5d-3e44-b664-d5345bb13be2",
  "source": "CROWN_FB_LIST",
  "sessions": [],
  "courtRoomId": 731816,
  "sessionDate": "2026-04-21",
  "sessionStartTime": "2026-04-21T10:00:00.000Z",
  "sessionEndTime": "2026-04-21T17:00:00.000Z",
  "durationInMinutes": 300,
  "isDraft": false,
  "businessType": "CR",
  "overbooked": false
}
