=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/schema/courtscheduler.crown.fallback.search.book.hearing.slots.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "hearingId": {
      "type": "string"
    },
    "courtCentreId": {
      "type": "string"
    },
    "courtRoomId": {
      "type": "string"
    },
    "hearingDate": {
      "type": "string"
    },
    "earliestHearingTime": {
      "type": "string"
    },
    "durationInMinutes": {
      "type": "integer",
      "minimum": 1,
      "maximum": 360
    },
    "source": {
      "type": "string",
      "enum": [
        "CROWN_FB_LIST",
        "CROWN_FB_ADJOURN",
        "CROWN_FB_UPDATE"
      ]
    }
  },
  "required": [
    "hearingId",
    "courtCentreId",
    "hearingDate",
    "durationInMinutes",
    "source"
  ]
}

=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/courtscheduler.crown.fallback.search.book.hearing.slots.json
{
  "hearingId": "7755fb96-e90a-4df2-8575-47841d8fbdd0",
  "courtCentreId": "07e45c88-9e5d-3e44-b664-d5345bb13be2",
  "courtRoomId": "731816c1-5ee4-373a-9bda-840e13a5bcb0",
  "hearingDate": "2026-04-21",
  "earliestHearingTime": "2026-04-21T09:00:00Z",
  "durationInMinutes": 10,
  "source": "CROWN_FB_LIST"
}
