=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/schema/courtscheduler.crown.fallback.search.book.hearing.slots.response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "hearingId": {
      "type": "string"
    },
    "courtScheduleId": {
      "type": "string"
    },
    "courtRoomId": {
      "type": "integer"
    },
    "sessionDate": {
      "type": "string",
      "format": "date"
    },
    "sessionStartTime": {
      "type": "string"
    },
    "sessionEndTime": {
      "type": "string"
    },
    "durationInMinutes": {
      "type": "integer"
    },
    "isDraft": {
      "type": "boolean"
    },
    "businessType": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "overbooked": {
      "type": "boolean"
    }
  },
  "required": [
    "hearingId",
    "courtScheduleId",
    "sessionDate",
    "durationInMinutes",
    "isDraft",
    "source"
  ]
}

=== hmcts/cpp-context-listing-courtscheduler/listingcourtscheduler-api/src/raml/json/courtscheduler.crown.fallback.search.book.hearing.slots.response.json
{
  "hearingId": "7755fb96-e90a-4df2-8575-47841d8fbdd0",
  "courtScheduleId": "5e2a3f91-9e5d-3e44-b664-d5345bb13be2",
  "courtRoomId": 731816,
  "sessionDate": "2026-04-21",
  "sessionStartTime": "2026-04-21T09:00:00Z",
  "sessionEndTime": "2026-04-21T17:00:00Z",
  "durationInMinutes": 10,
  "isDraft": false,
  "businessType": "CR",
  "source": "CROWN_FB_LIST",
  "overbooked": false
}
